markdown:         rdiscount
pygments:         true
paginate:         8

title:            
url:              hxsnow10.github.io
feed:             atom.xml
author:
    name:         hxsnow10
    email:        xiahahaha01@gmail.com     
description:      "xiahahaha01's blog"

copyright:
    - Design by <a href="https://github.com/pua/pua.github.com" rel="author" title="ImPUA">ImPUA</a> Powered by <a href="http://github.com/mojombo/jekyll/" rel="friend" title="Jekyll" target="_blank">Jekyll</a>
    - "&copy; Copyright 2012, All Rights Reserved."

